[package]
name = "task-manager"
version = "0.1.0"
edition = "2018"
authors = ["Iaroslav Sorokin <iaroslav.sorokin@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.2.0", package = "gtk4" }
